use_default_settings: true

general:
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "0932foqfas1r3wqfhioqaosif3198fdsajoqojafij9afj3af8safkj"

ui:
  static_use_hash: true